In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras


In [28]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiments = np.array([1,1,1,1,1,0,0,0,0,0])

In [29]:
from tensorflow.keras.preprocessing.text import one_hot
# one_hot('text', vocab_size)


vocab_size = 50
encoded_reviews = [one_hot(review, vocab_size) for review in reviews]
encoded_reviews


[[8, 39],
 [25, 25],
 [49, 47],
 [49, 48, 9],
 [29, 27, 31],
 [5, 39],
 [17, 27, 32],
 [48, 12],
 [48, 20],
 [37, 37]]

In [31]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding="post")
padded_reviews

array([[ 8, 39,  0],
       [25, 25,  0],
       [49, 47,  0],
       [49, 48,  9],
       [29, 27, 31],
       [ 5, 39,  0],
       [17, 27, 32],
       [48, 12,  0],
       [48, 20,  0],
       [37, 37,  0]], dtype=int32)

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten
embed_vector_size = 5

model = keras.models.Sequential()
model.add(Embedding(vocab_size, embed_vector_size, input_length=3, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation="sigmoid"))


In [33]:
X = padded_reviews
y = sentiments

In [34]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [35]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 5)              250       
_________________________________________________________________
flatten_4 (Flatten)          (None, 15)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 16        
Total params: 266
Trainable params: 266
Non-trainable params: 0
_________________________________________________________________


In [36]:
model.fit(X, y, epochs=10, verbose=0)

2021-12-12 09:30:09.429346: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-12-12 09:30:09.431864: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2021-12-12 09:30:09.564263: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


In [38]:
loss, accuracy = model.evaluate(X,y)

1/1 [==============================] - 0s 59ms/step - loss: 0.6830 - accuracy: 0.8000


2021-12-12 09:30:53.755144: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


In [40]:
weights = model.get_layer("embedding").get_weights()[0]


In [41]:
weights[11]

array([-0.02638308, -0.00218799, -0.03079735, -0.04374829,  0.00323089],
      dtype=float32)

In [42]:
weights[3]

array([-0.0117569 ,  0.03181029,  0.04219042, -0.00172433,  0.04710234],
      dtype=float32)