In [18]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [19]:
data = keras.datasets.mnist.load_data()
data

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [69]:
(X_train, y_train), (X_test, y_test) = data
X_train[0] 

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [70]:
X_train.shape

(60000, 28, 28)

In [71]:
# scale
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') /255
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [103]:
X_train = X_train.reshape(len(X_train), 28*28)
X_train.shape

(60000, 784)

In [73]:
X_test = X_test.reshape(len(X_test), 28*28)

In [74]:
model = keras.Sequential([
    keras.layers.Dense(10, input_shape=(784,), activation="relu"),
        keras.layers.Dense(10, input_shape=(784,), activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [75]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
  32/1875 [..............................] - ETA: 9s - loss: 2.1761 - accuracy: 0.2285 

2021-12-06 22:42:40.112747: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


1875/1875 [==============================] - 7s 4ms/step - loss: 0.5059 - accuracy: 0.8604
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2955 - accuracy: 0.9165
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2707 - accuracy: 0.9244
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2577 - accuracy: 0.9280
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2493 - accuracy: 0.9305


In [87]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 4ms/step - loss: 0.2578 - accuracy: 0.9262


[0.2578335702419281, 0.9262000322341919]

In [88]:
y_predicted =model.predict(X_test)

In [93]:
y_predicted_labels = [np.argmax(i) for i in y_predicted]

In [94]:
y_predicted[1]

array([1.6454486e-03, 3.7877919e-04, 9.8827165e-01, 5.3997505e-03,
       2.0727030e-15, 1.8319832e-03, 2.2944079e-03, 1.1909218e-13,
       1.7801429e-04, 6.3857059e-11], dtype=float32)

In [95]:
np.argmax(y_predicted[1])

2

In [99]:
cm = tf.math.confusion_matrix(labels=y_test, predictions=y_predicted_labels)
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 953,    0,    6,    4,    1,    9,    3,    2,    2,    0],
       [   0, 1120,    2,    3,    0,    1,    3,    2,    4,    0],
       [   5,   11,  938,   30,    5,    2,    9,    5,   23,    4],
       [   0,    2,   16,  953,    1,   15,    0,    8,   12,    3],
       [   3,    2,    6,    4,  888,    0,    9,    8,   11,   51],
       [   8,    4,    6,   45,    6,  778,    9,    6,   24,    6],
       [  13,    3,   11,    2,    7,   12,  904,    3,    3,    0],
       [   1,   11,   27,   17,    5,    0,    0,  934,    1,   32],
       [   8,    8,    9,   36,    8,   21,    8,    6,  861,    9],
       [   9,    9,    1,   15,   16,    9,    0,    9,    8,  933]],
      dtype=int32)>